### ISSUE TITLE
Keyword arguments

### ISSUE THREAD

**Issue by moisespsena** [ozanh/ugo#13]
Hello!
Do you have plans to supports keyword arguments?

**Comment by ozanh** [comment]
Hi, I haven't planned anything keyword arguments. It requires too much effort for now. I think it is better to focus on quick wins like basic modules. What do you think?

**Comment by moisespsena** [comment]
> Hi, I haven't planned anything keyword arguments. It requires too much effort for now. I think it is better to focus on quick wins like basic modules. What do you think?

I made this implementation for Tengo[1], but still the result of the benchmark was not satisfactory. If you can take a look and tell me what you think it would be interesting. If you consider it pertinent, I can make a Fork and implement this solution here. 

[1] https://github.com/d5/tengo/pull/371

**Comment by ozanh** [comment]
Closing this for now. However, I may change the Call method signature or add a new interface not to break backward compatibility in the near future for some improvements. We can discuss this at that time.
