### ISSUE TITLE
Would like to call function from a ugo.Function

### ISSUE THREAD

**Issue by kcsampson** [ozanh/ugo#25]
I tried getting this to work on tengo, there was a mention of it possibly working on ugo.  Problem is with ugo, re-entering the VM is deadlocked due to the lock.  Here's the code I want to run:

package meta_ugo

import (
	"errors"
	"github.com/ozanh/ugo"
	"testing"
)

func TestReenterUgo(t *testing.T) {

	script := `
   
      var abc = [123,456,789]

      arr := [123,456,789]
      
      global filter
         
      smalls := filter( arr, func(item){ 
             printf("my lambda.... %s", item)
             return item < 500
          })
         
      printf("smalls=%v", smalls)
   `

	tfiltSetVM, tfilter := makeUgoFilter()

	igm := ugo.Map{"filter": &ugo.Function{Value: tfilter}}

	if c, err := ugo.Compile([]byte(script), ugo.DefaultCompilerOptions); err != nil {

		t.Error(err)

	} else if vm := ugo.NewVM(c); false {

	} else if tfiltSetVM(vm); false {

	} else if res, err := vm.Run(igm); err != nil {

		t.Error(err)

	} else {

		t.Logf("res = %v", res)
	}
}

type ugoFilter struct {
	vm *ugo.VM
}

func makeUgoFilter() (func(*ugo.VM), func(...ugo.Object) (ugo.Object, error)) {

	tf := &ugoFilter{}

	return func(mv *ugo.VM) {
			tf.vm = mv
			return
		},
		func(args ...ugo.Object) (reg ugo.Object, err error) {
			requreMsg := "Requires an array and a callable func"
			if len(args) != 2 {
				err = errors.New(requreMsg)
				return
			}

			if a, arrOk := args[0].(ugo.Array); !arrOk {

				err = errors.New(requreMsg)
				return
			} else if c, callbackOk := args[1].(*ugo.CompiledFunction); !callbackOk {

				err = errors.New(requreMsg)
				return
			} else {

				result := ugo.Array{}

				for _, x := range a {
					if res, err := tf.vm.RunCompiledFunction(c, nil, x); err != nil {
						return nil, err
					} else if !res.IsFalsy() {

						result = append(result, x)
					}

				}
			}

			return

		}
}

**Comment by ozanh** [comment]
Hi @kcsampson ,
Currently, neither Tengo nor uGO supports running a function created in a script on Go side while VM is actively running.
But!, I've just started to develop this feature for my company because we actively use uGO, and this requirement popped up. Yesterday, I finalized my first experimental development to enable this feature. Here is a straightforward example code from my tests;

```go
func Benchmark_Invoker(b *testing.B) {
	apply := &Function{
		ValueEx: func(c Call) (Object, error) {
			inv := NewInvoker(c.VM(), c.Get(0))
			inv.AcquireFromPool()
			defer inv.Release()
			return inv.Invoke(c.Get(1), c.Get(2))
		},
	}

	scr := []byte(`
param (p1, p2)
global apply

sum := func(a, b) {
	return a + b
}

return apply(sum, p1, p2)
`)
	bc, err := Compile(scr, DefaultCompilerOptions)
	if err != nil {
		b.Fatal(err)
	}

	vm := NewVM(bc)
	globals := Map{"apply": apply}
	b.ResetTimer()

	for i := 0; i < b.N; i++ {
		ret, err := vm.Run(globals, Int(1), Int(2))
		if err != nil {
			b.Fatal(err)
		}
		if ret != Int(3) {
			b.Fatal("wrong result")
		}
	}
}
```
I haven't pushed new Invoker feature yet, but I will probably push this, next week.
We've been using `dev` branch actively. At the end of May, all changes will be merged into `main` because there are many new features in dev branch.

**Comment by kcsampson** [comment]
Awesome thanks, just tested it and works.  I will play around with it some.
