### ISSUE TITLE
Is uGO production ready.

### ISSUE THREAD

**Issue by matwachich** [ozanh/ugo#31]
I want to know if uGO is production ready, for some commercial grade product?
Thanks :)

Do you use it in some robuste software?

**Comment by ozanh** [comment]
Hi @matwachich 
uGO has been used in production for more than two years at the company where I work. It's main purpose is threat hunting in the security domain. Currently, more than 100K client or server machines run our products daily. I am not part of the team that develops the product in which uGO is used but I provided some help in the past. Next year, our products will run on millions of machines including uGO. This is the only production usage I am aware of.
